version: "2"
services:
  web:
    build:
      context: .
      dockerfile: application.dockerfile
    ports:
      - "80:8000"
    depends_on:
      - db
    volumes:
      - /var:/var
  db:
    build:
      context: .
      dockerfile: mongodb.dockerfile
    volumes:
      - /data/db:/data/db
      - /var:/var
