version: "2"
services:
  web:
    build:
      context: .
      dockerfile: webapp.dockerfile
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: mongodb.dockerfile
    volumes:
      - /srv/gimmejson/mongo/db:/data/db
      - /srv/gimmejson/mongo/:/var/log/mongod
