#!/bin/bash

# checkout master branch
git --work-tree /srv/webapp --git-dir /srv/webapp.git/ checkout -f master

echo "Deploying commit: `git rev-parse HEAD`"

cd /srv/webapp
docker-compose up -d --build
docker-compose logs
