#!/bin/bash

# checkout master branch
git --work-tree /srv/gimmejson/src --git-dir /srv/gimmejson/gimmejson.git/ checkout -f master

echo "Deploying commit: `git rev-parse HEAD`"

cd /srv/gimmejson/src
docker-compose up -d --build
docker-compose logs
